### ISSUE TITLE
[Bug] Find command only finds from prefix (Not sure if bug or intended)

### ISSUE THREAD

**Issue by Jemereny** [CS2103AUG2017-T15-B4/addressbook-level4#236]
![media](https://user-images.githubusercontent.com/26541648/32363350-ee0bbdfe-c0a9-11e7-84c9-47cd98155b1c.gif)

1. Have a contact named "Alex Yeoh"
2. Able to find "Ale"
2. Able to find "Alex"
3. Able to find "Yeo"
3. Able to find "Yeoh"
4. Cannot find "lex"

**Partial words will be matched e.g. Ha will match Hans.** (In user guide)

**Comment by ALim95** [comment]
yeah its as intended, i've updated the userguide to reflect how find command works. thanks for pointing this out!
