### ISSUE TITLE
code quality comments for Alim95

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B4/addressbook-level4#258]
![image](https://user-images.githubusercontent.com/1023494/32654082-f351d0be-c644-11e7-992d-259ef7031410.png)
- header comments don't follow the convention we specify (this and a few others)

![image](https://user-images.githubusercontent.com/1023494/32654158-3359b3c0-c645-11e7-9da3-412787ed0364.png)
- can split these to multiple lines for better readability

@ALim95 FYA

**Comment by ALim95** [comment]
![image](https://user-images.githubusercontent.com/31213216/32685871-252acc04-c6d5-11e7-94db-55c58cdedd03.png)

@okkhoy hi tutor do you mean split like this?
