### ISSUE TITLE
code quality comments for aziziazfar

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B4/addressbook-level4#259]
![image](https://user-images.githubusercontent.com/1023494/32654262-8b18ff80-c645-11e7-8c92-dd41483746f5.png)
- when I read the code I don't get the connect between args length 2 and args contains ~. Can try to reorganize the code to follow SRP

![image](https://user-images.githubusercontent.com/1023494/32654311-b09502ae-c645-11e7-8297-496058e3349c.png)
- improper collation?

@aziziazfar FYA

**Comment by aziziazfar** [comment]
Alright, thanks Akshay!
