### ISSUE TITLE
code quality comments for deep4k

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T15-B4/addressbook-level4#260]
![image](https://user-images.githubusercontent.com/1023494/32654341-d1af51a6-c645-11e7-850e-b6e780078ed5.png)
- better would be `Creates an alias command`

![image](https://user-images.githubusercontent.com/1023494/32654392-08b6db74-c646-11e7-962b-dace8e928422.png)
- when it is obvious from the method signature, no need to have header comments that are  blank / have only param string

![image](https://user-images.githubusercontent.com/1023494/32654426-2d128bf8-c646-11e7-9f5d-5767e3b09e0d.png)
- the code says it all, why redundant comment

![image](https://user-images.githubusercontent.com/1023494/32654553-59475cb2-c646-11e7-9970-c686fe2dd4bf.png)
- similar comment as #259 

- man! too long, i give up :stuck_out_tongue_winking_eye: 

@deep4k  fya

**Comment by deep4k** [comment]
Thanks ! 👍
