### ISSUE TITLE
[BUG] even there are no remarks, remarks still can be removed

### ISSUE THREAD

**Issue by junyango** [CS2103AUG2017-T15-B4/addressbook-level4#268]
also, the help overlay shows 

![bluebird bug report](https://user-images.githubusercontent.com/28534858/32696609-92669d1a-c7b7-11e7-850f-64ffcafb8b39.gif)

under add remark, it is shown as remark 1. however, that is the command for removing remarks.

**Comment by deep4k** [comment]
Yeah your right, the help overlay will be updated

remark 1 will remove remarks
remark 1 r/test will add remark 'test'

Thanks!  👍
