### ISSUE TITLE
As a user, I can select a contact and search for his information online

### ISSUE THREAD

**Issue by ALim95** [CS2103AUG2017-T15-B4/addressbook-level4#7]
... in case i forget who that person is.

**Comment by deep4k** [comment]
Online in the sense that we search matching contact on social media platforms?
I think its pretty good to have (Probably falls in Nice to Have?)

**Comment by ALim95** [comment]
Oh no this is actually the function that is already in addressbook.
Its the select function.

**Comment by ALim95** [comment]
But hey i think what you suggested is pretty nice to have

**Comment by deep4k** [comment]
Oh, yea the default one provided is probably not so useful but the social media one might be nice to have. I moved this issue it the project board
